import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import Ajv2020 from "ajv/dist/2020";
import addFormats from "ajv-formats";
import openapiTS, { astToString } from "openapi-typescript";
import { format, resolveConfig } from "prettier";
import { describe, expect, it } from "vitest";

import { CONTRACT_VERSION, SCHEMA_IDS } from "./src/index";

const here = dirname(fileURLToPath(import.meta.url));
const load = (rel: string) => JSON.parse(readFileSync(join(here, rel), "utf8"));

const ajv = new Ajv2020({ strict: false, allErrors: true });
addFormats(ajv);

const schemaFiles = readdirSync(join(here, "schemas")).filter((f) => f.endsWith(".schema.json"));

// Register every schema before compiling anything: reader-response/v1 $refs
// source-span/v1 and financial-fact/v1 by $id, so lazy per-file compilation
// order must not matter.
for (const file of schemaFiles) {
  ajv.addSchema(load(`schemas/${file}`));
}

describe("contract schemas", () => {
  it("every schema compiles and has a versioned $id", () => {
    for (const file of schemaFiles) {
      const schema = load(`schemas/${file}`);
      expect(schema.$id, file).toMatch(/^https:\/\/contracts\.fel\.dev\/schemas\/[a-z-]+\/v\d+$/);
      expect(schema["x-fel-version"], file).toMatch(/^\d+\.\d+\.\d+$/);
      // getSchema compiles the registered schema (and its $refs) on demand.
      expect(() => ajv.getSchema(schema.$id), file).not.toThrow();
      expect(ajv.getSchema(schema.$id), file).toBeDefined();
    }
  });

  it("every fixture validates against its schema", () => {
    for (const file of schemaFiles) {
      const name = file.replace(".schema.json", "");
      const validate = ajv.getSchema(`https://contracts.fel.dev/schemas/${name}/v1`);
      expect(validate, name).toBeDefined();
      const fixture = load(`fixtures/${name}.json`);
      const ok = validate!(fixture);
      expect(ok, `${name}: ${JSON.stringify(validate!.errors)}`).toBe(true);
    }
  });

  it("claim status and citation entailment are the closed spec sets", () => {
    const claim = load("schemas/claim.schema.json");
    expect(claim.properties.status.enum).toEqual([
      "supported",
      "partially_supported",
      "contradicted",
      "derived",
      "unsupported",
    ]);
    const citation = load("schemas/citation.schema.json");
    expect(citation.properties.entailment.enum).toEqual([
      "entailed",
      "partial",
      "contradictory",
      "irrelevant",
    ]);
  });

  it("monetary values are decimal strings, never floats", () => {
    const fact = load("schemas/financial-fact.schema.json");
    expect(fact.properties.value.type).toBe("string");
    const validate = ajv.getSchema(SCHEMA("financial-fact"));
    const bad = { ...load("fixtures/financial-fact.json"), value: 1250000000 };
    expect(validate!(bad)).toBe(false);
  });

  it("job terminal states are exactly succeeded/failed/cancelled", () => {
    const job = load("schemas/job-envelope.schema.json");
    const states: string[] = job.properties.status.enum;
    expect(states).toEqual(["queued", "claimed", "running", "succeeded", "failed", "cancelled"]);
  });
});

describe("contract version identity (VERSIONING.md)", () => {
  it("openapi info.version and CONTRACT_VERSION agree on the 0.2.0 minor bump", () => {
    const yaml = readFileSync(join(here, "openapi/openapi.yaml"), "utf8");
    const infoVersion = /^ {2}version: (\d+\.\d+\.\d+)$/m.exec(yaml)?.[1];
    expect(infoVersion).toBe(CONTRACT_VERSION);
    expect(CONTRACT_VERSION).toBe("0.2.0");
  });

  it("SCHEMA_IDS covers every schema file (and nothing else)", () => {
    const fromFiles = schemaFiles
      .map((f) => `https://contracts.fel.dev/schemas/${f.replace(".schema.json", "")}/v1`)
      .sort();
    expect(Object.values(SCHEMA_IDS).slice().sort()).toEqual(fromFiles);
  });
});

describe("generated client drift (check:generated in-suite)", () => {
  it("src/generated/api.ts is exactly the prettier-formatted openapi-typescript output — hand edits fail", async () => {
    const banner =
      "/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n";
    const ast = await openapiTS(pathToFileURL(join(here, "openapi/openapi.yaml")));
    const apiPath = join(here, "src/generated/api.ts");
    // The committed file follows the repo convention: generator output run
    // through prettier with the repo config (see the generate script).
    const prettierConfig = await resolveConfig(apiPath);
    const expected = await format(banner + astToString(ast), {
      ...prettierConfig,
      parser: "typescript",
    });
    const committed = readFileSync(apiPath, "utf8");
    expect(committed).toBe(expected);
  });

  it("generated surface exposes the reader path and the promoted fact type", () => {
    const api = readFileSync(join(here, "src/generated/api.ts"), "utf8");
    expect(api).toContain('"/v1/documents/{documentId}/reader"');
    expect(api).toContain("ReaderResponse:");
    // FinancialFact aliases the file-$ref'd frozen financial-fact/v1 schema,
    // so apps/web can drop its hand mirror.
    expect(api).toMatch(/FinancialFact: components\["schemas"\]\["financial-fact\.schema"\];/);
  });
});

type SpanRecord = {
  id: string;
  span: {
    document_version_id: string;
    section_id: string;
    start_char: number;
    end_char: number;
    text_hash: string;
  };
};
type FactRecord = {
  id: string;
  document_version_id: string;
  duplicate_of?: string;
  restates?: string;
  fact: { source_span_id: string };
};
type Section = {
  id: string;
  document_version_id: string;
  ord: number;
  start_char: number;
  end_char: number;
  content: string;
};
type DocBlock = {
  meta: { id: string; entity_id: string; published_at: string };
  document_version_id: string;
  sections?: Section[];
  spans: SpanRecord[];
  facts: FactRecord[];
};

describe("reader-response fixture invariants (ADR-0005)", () => {
  const fixture = load("fixtures/reader-response.json") as {
    as_of: string;
    corpus_version_id: string | null;
    selection_policy: string;
    document: DocBlock;
    siblings: DocBlock[];
  };
  const blocks: DocBlock[] = [fixture.document, ...fixture.siblings];
  const sha256 = (s: string) => "sha256:" + createHash("sha256").update(s, "utf8").digest("hex");

  it("document ids and selected version ids are distinct, never interchangeable", () => {
    const docIds = blocks.map((b) => b.meta.id);
    const verIds = blocks.map((b) => b.document_version_id);
    expect(new Set([...docIds, ...verIds]).size).toBe(docIds.length + verIds.length);
    for (const b of blocks) expect(b.meta.id).not.toBe(b.document_version_id);
  });

  it("every section, span, and fact belongs to its block's selected version", () => {
    for (const b of blocks) {
      for (const s of b.sections ?? []) expect(s.document_version_id).toBe(b.document_version_id);
      for (const r of b.spans) expect(r.span.document_version_id).toBe(b.document_version_id);
      for (const f of b.facts) expect(f.document_version_id).toBe(b.document_version_id);
    }
  });

  it("facts never reference spans absent from their own block", () => {
    for (const b of blocks) {
      const spanIds = new Set(b.spans.map((r) => r.id));
      for (const f of b.facts) expect(spanIds.has(f.fact.source_span_id), f.id).toBe(true);
    }
  });

  it("duplicate_of / restates resolve to fact ids present in the response", () => {
    const factIds = new Set(blocks.flatMap((b) => b.facts.map((f) => f.id)));
    let linkageSeen = 0;
    for (const b of blocks) {
      for (const f of b.facts) {
        if (f.duplicate_of) {
          linkageSeen += 1;
          expect(factIds.has(f.duplicate_of), f.id).toBe(true);
        }
        if (f.restates) {
          linkageSeen += 1;
          expect(factIds.has(f.restates), f.id).toBe(true);
        }
      }
    }
    // The fixture must actually exercise duplicate AND amendment linkage.
    expect(linkageSeen).toBeGreaterThanOrEqual(2);
  });

  it("section offsets are canonical document-global and content is the exact slice length", () => {
    const sections = fixture.document.sections!;
    expect(sections.length).toBeGreaterThan(2);
    for (const s of sections) {
      expect(s.end_char).toBeGreaterThanOrEqual(s.start_char);
      expect(s.content.length).toBe(s.end_char - s.start_char);
    }
    // Non-first sections start where the canonical text has already advanced.
    const ordered = [...sections].sort((a, b) => a.ord - b.ord);
    for (let i = 1; i < ordered.length; i += 1) {
      expect(ordered[i]!.start_char).toBeGreaterThan(0);
      expect(ordered[i]!.start_char).toBeGreaterThanOrEqual(ordered[i - 1]!.end_char);
    }
  });

  it("spans use global offsets: local anchor is start_char - section.start_char and hash-verifies", () => {
    const sections = new Map(fixture.document.sections!.map((s) => [s.id, s]));
    for (const r of fixture.document.spans) {
      const sec = sections.get(r.span.section_id);
      expect(sec, r.id).toBeDefined();
      // Containment in GLOBAL coordinates.
      expect(r.span.start_char).toBeGreaterThanOrEqual(sec!.start_char);
      expect(r.span.end_char).toBeLessThanOrEqual(sec!.end_char);
      // The quoted text re-verifies against the section-content slice.
      const local = sec!.content.slice(
        r.span.start_char - sec!.start_char,
        r.span.end_char - sec!.start_char,
      );
      expect(sha256(local), r.id).toBe(r.span.text_hash);
    }
  });

  it("regression: a non-first-section span's GLOBAL start exceeds its section-content length", () => {
    const sections = new Map(fixture.document.sections!.map((s) => [s.id, s]));
    const witness = fixture.document.spans.find((r) => {
      const sec = sections.get(r.span.section_id)!;
      return sec.ord > 0 && r.span.start_char > sec.content.length;
    });
    // If offsets were section-local this span would be unrepresentable;
    // web's local anchor is start_char - section.start_char (issue #87 B).
    expect(witness).toBeDefined();
  });

  it("cutoff and pin semantics: everything visible at published_at <= as_of; null pin means latest_parsed", () => {
    const asOf = Date.parse(fixture.as_of);
    for (const b of blocks) expect(Date.parse(b.meta.published_at)).toBeLessThanOrEqual(asOf);
    expect(fixture.corpus_version_id).toBeNull();
    expect(fixture.selection_policy).toBe("latest_parsed");
    // Sibling evidence for amendment comparison: same entity throughout.
    for (const b of blocks) expect(b.meta.entity_id).toBe(fixture.document.meta.entity_id);
  });

  it("every fact payload validates against the frozen financial-fact/v1 schema", () => {
    const validate = ajv.getSchema(SCHEMA("financial-fact"))!;
    for (const b of blocks) {
      for (const f of b.facts) {
        expect(validate(f.fact), `${f.id}: ${JSON.stringify(validate.errors)}`).toBe(true);
      }
    }
  });
});

function SCHEMA(name: string): string {
  return `https://contracts.fel.dev/schemas/${name}/v1`;
}
