import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import Ajv2020 from "ajv/dist/2020";
import addFormats from "ajv-formats";
import openapiTS, { astToString } from "openapi-typescript";
import { format, resolveConfig } from "prettier";
import { describe, expect, it } from "vitest";

import { CONTRACT_VERSION, SCHEMA_IDS } from "./src/index";

const here = dirname(fileURLToPath(import.meta.url));
const load = (rel: string) => JSON.parse(readFileSync(join(here, rel), "utf8"));

const ajv = new Ajv2020({ strict: false, allErrors: true });
addFormats(ajv);

const schemaFiles = readdirSync(join(here, "schemas")).filter((f) => f.endsWith(".schema.json"));

// Register every schema before compiling anything: reader-response/v1 $refs
// source-span/v1 and financial-fact/v1 by $id, so lazy per-file compilation
// order must not matter.
for (const file of schemaFiles) {
  ajv.addSchema(load(`schemas/${file}`));
}

describe("contract schemas", () => {
  it("every schema compiles and has a versioned $id", () => {
    for (const file of schemaFiles) {
      const schema = load(`schemas/${file}`);
      expect(schema.$id, file).toMatch(/^https:\/\/contracts\.fel\.dev\/schemas\/[a-z-]+\/v\d+$/);
      expect(schema["x-fel-version"], file).toMatch(/^\d+\.\d+\.\d+$/);
      // getSchema compiles the registered schema (and its $refs) on demand.
      expect(() => ajv.getSchema(schema.$id), file).not.toThrow();
      expect(ajv.getSchema(schema.$id), file).toBeDefined();
    }
  });

  it("every fixture validates against its schema", () => {
    for (const file of schemaFiles) {
      const name = file.replace(".schema.json", "");
      const validate = ajv.getSchema(`https://contracts.fel.dev/schemas/${name}/v1`);
      expect(validate, name).toBeDefined();
      const fixture = load(`fixtures/${name}.json`);
      const ok = validate!(fixture);
      expect(ok, `${name}: ${JSON.stringify(validate!.errors)}`).toBe(true);
    }
  });

  it("claim status and citation entailment are the closed spec sets", () => {
    const claim = load("schemas/claim.schema.json");
    expect(claim.properties.status.enum).toEqual([
      "supported",
      "partially_supported",
      "contradicted",
      "derived",
      "unsupported",
    ]);
    const citation = load("schemas/citation.schema.json");
    expect(citation.properties.entailment.enum).toEqual([
      "entailed",
      "partial",
      "contradictory",
      "irrelevant",
    ]);
  });

  it("monetary values are decimal strings, never floats", () => {
    const fact = load("schemas/financial-fact.schema.json");
    expect(fact.properties.value.type).toBe("string");
    const validate = ajv.getSchema(SCHEMA("financial-fact"));
    const bad = { ...load("fixtures/financial-fact.json"), value: 1250000000 };
    expect(validate!(bad)).toBe(false);
  });

  it("job terminal states are exactly succeeded/failed/cancelled", () => {
    const job = load("schemas/job-envelope.schema.json");
    const states: string[] = job.properties.status.enum;
    expect(states).toEqual(["queued", "claimed", "running", "succeeded", "failed", "cancelled"]);
  });
});

describe("contract version identity (VERSIONING.md)", () => {
  it("openapi info.version and CONTRACT_VERSION agree on the 0.3.0 minor bump", () => {
    const yaml = readFileSync(join(here, "openapi/openapi.yaml"), "utf8");
    const infoVersion = /^ {2}version: (\d+\.\d+\.\d+)$/m.exec(yaml)?.[1];
    expect(infoVersion).toBe(CONTRACT_VERSION);
    expect(CONTRACT_VERSION).toBe("0.3.0");
  });

  it("SCHEMA_IDS covers every schema file (and nothing else)", () => {
    const fromFiles = schemaFiles
      .map((f) => `https://contracts.fel.dev/schemas/${f.replace(".schema.json", "")}/v1`)
      .sort();
    expect(Object.values(SCHEMA_IDS).slice().sort()).toEqual(fromFiles);
  });
});

describe("generated client drift (check:generated in-suite)", () => {
  it("src/generated/api.ts is exactly the prettier-formatted openapi-typescript output — hand edits fail", async () => {
    const banner =
      "/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n";
    const ast = await openapiTS(pathToFileURL(join(here, "openapi/openapi.yaml")));
    const apiPath = join(here, "src/generated/api.ts");
    // The committed file follows the repo convention: generator output run
    // through prettier with the repo config (see the generate script).
    const prettierConfig = await resolveConfig(apiPath);
    const expected = await format(banner + astToString(ast), {
      ...prettierConfig,
      parser: "typescript",
    });
    const committed = readFileSync(apiPath, "utf8");
    expect(committed).toBe(expected);
  });

  it("generated surface exposes the reader path and the promoted fact type", () => {
    const api = readFileSync(join(here, "src/generated/api.ts"), "utf8");
    expect(api).toContain('"/v1/documents/{documentId}/reader"');
    expect(api).toContain("ReaderResponse:");
    // FinancialFact aliases the file-$ref'd frozen financial-fact/v1 schema,
    // so apps/web can drop its hand mirror.
    expect(api).toMatch(/FinancialFact: components\["schemas"\]\["financial-fact\.schema"\];/);
  });

  it("generated surface exposes observable retrieval paths and required resolved pins", () => {
    const api = readFileSync(join(here, "src/generated/api.ts"), "utf8");
    expect(api).toContain('"/v1/workspaces/{workspaceId}/queries"');
    expect(api).toContain('"/v1/queries/{queryId}"');
    expect(api).toContain('"/v1/queries/{queryId}/reruns"');
    expect(api).toContain('"/v1/retrieval-runs/{runId}"');
    expect(api).toContain('"/v1/retrieval-runs/{runId}/events"');
    expect(api).toContain('"/v1/retrieval-runs/{runId}/feedback"');
    expect(api).toContain("CreateQuery:");
    expect(api).toContain("QueryPlan:");
    expect(api).toContain("RetrievalEvent:");
    expect(api).toContain("RetrievalTrace:");
    // Optional create pins; required resolved pins on the plan.
    expect(api).toMatch(/CreateQuery:[\s\S]*index_version_id\?:/);
    expect(api).toMatch(/QueryPlan:[\s\S]*corpus_version_id: string;/);
    expect(api).toMatch(/QueryPlan:[\s\S]*index_version_id: string;/);
  });
});

describe("observable retrieval fixtures (ADR-0006)", () => {
  it("query-plan requires resolved corpus and index pins", () => {
    const validate = ajv.getSchema(SCHEMA_IDS.queryPlan)!;
    const plan = load("fixtures/query-plan.json");
    expect(validate(plan)).toBe(true);
    for (const pin of ["corpus_version_id", "index_version_id"] as const) {
      const unpinned = { ...plan };
      delete (unpinned as Record<string, unknown>)[pin];
      expect(validate(unpinned), pin).toBe(false);
    }
    expect(validate({ ...plan, corpus_version_id: null })).toBe(false);
  });

  it("query-plan rejects non-positive retrieval budgets", () => {
    const validate = ajv.getSchema(SCHEMA_IDS.queryPlan)!;
    const plan = load("fixtures/query-plan.json") as {
      budgets: Record<string, number>;
    };
    for (const name of ["lane_top_k", "fused_top_k", "context_items", "timeout_ms"]) {
      expect(validate({ ...plan, budgets: { ...plan.budgets, [name]: 0 } }), name).toBe(false);
    }
  });

  it("retrieval-event sequences are positive and typed for SSE", () => {
    const validate = ajv.getSchema(SCHEMA_IDS.retrievalEvent)!;
    const event = load("fixtures/retrieval-event.json");
    expect(validate(event)).toBe(true);
    expect(validate({ ...event, seq: 0 })).toBe(false);
    expect(validate({ ...event, type: "not_an_event" })).toBe(false);
  });

  it("retrieval-event has a terminal event for cancelled runs", () => {
    const validate = ajv.getSchema(SCHEMA_IDS.retrievalEvent)!;
    const event = load("fixtures/retrieval-event.json");
    expect(validate({ ...event, type: "run_cancelled" }), JSON.stringify(validate.errors)).toBe(
      true,
    );
  });

  it("retrieval-trace lineage pins match the plan index and events are ordered", () => {
    const validate = ajv.getSchema(SCHEMA_IDS.retrievalTrace)!;
    const trace = load("fixtures/retrieval-trace.json") as {
      run_id: string;
      status: string;
      plan: { index_version_id: string };
      lineage: { index_version_id: string };
      events: Array<{ run_id: string; seq: number; type: string }>;
      candidates: Array<{ item_id: string; source_span_id: string }>;
      claims: Array<{
        citations: Array<{ item_id: string; source_span_id: string }>;
      }>;
    };
    expect(validate(trace), JSON.stringify(validate.errors)).toBe(true);
    expect(trace.lineage.index_version_id).toBe(trace.plan.index_version_id);
    for (const [index, event] of trace.events.entries()) {
      expect(event.run_id).toBe(trace.run_id);
      if (index > 0) expect(event.seq).toBeGreaterThan(trace.events[index - 1]!.seq);
    }
    const expectedTerminalEvent: Record<string, string> = {
      succeeded: "run_completed",
      abstained: "run_abstained",
      failed: "run_failed",
      cancelled: "run_cancelled",
    };
    if (trace.status in expectedTerminalEvent) {
      expect(trace.events.at(-1)?.type).toBe(expectedTerminalEvent[trace.status]);
    }
    const candidateEvidence = new Set(
      trace.candidates.map((candidate) => `${candidate.item_id}:${candidate.source_span_id}`),
    );
    for (const claim of trace.claims) {
      for (const citation of claim.citations) {
        expect(candidateEvidence.has(`${citation.item_id}:${citation.source_span_id}`)).toBe(true);
      }
    }
  });

  it("retrieval-trace candidates never exceed the inclusive effective cutoff", () => {
    const trace = load("fixtures/retrieval-trace.json") as {
      plan: { effective_as_of: string };
      candidates: Array<{ published_at: string }>;
    };
    const cutoff = Date.parse(trace.plan.effective_as_of);
    for (const candidate of trace.candidates) {
      expect(Date.parse(candidate.published_at)).toBeLessThanOrEqual(cutoff);
    }
  });

  it("retrieval-trace rejects non-decimal score strings", () => {
    const validate = ajv.getSchema(SCHEMA_IDS.retrievalTrace)!;
    const trace = load("fixtures/retrieval-trace.json") as {
      candidates: Array<{ contributions: Array<{ raw_score: string }> }>;
    };
    const invalid = structuredClone(trace);
    invalid.candidates[0]!.contributions[0]!.raw_score = "NaN";
    expect(validate(invalid)).toBe(false);
  });

  it("evidence feedback can supersede an earlier append-only record", () => {
    const validate = ajv.getSchema(SCHEMA_IDS.evidenceFeedback)!;
    const feedback = load("fixtures/evidence-feedback.json");
    expect(
      validate({
        ...feedback,
        supersedes_feedback_id: "a7b8c9d0-e1f2-3456-0123-567890123456",
      }),
      JSON.stringify(validate.errors),
    ).toBe(true);
  });
});

type SpanRecord = {
  id: string;
  span: {
    document_version_id: string;
    section_id: string;
    start_char: number;
    end_char: number;
    text_hash: string;
  };
};
type FactRecord = {
  id: string;
  document_version_id: string;
  duplicate_of?: string;
  restates?: string;
  fact: { source_span_id: string };
};
type Section = {
  id: string;
  document_version_id: string;
  ord: number;
  start_char: number;
  end_char: number;
  content: string;
};
type DocBlock = {
  meta: { id: string; entity_id: string; published_at: string };
  document_version_id: string;
  sections?: Section[];
  spans: SpanRecord[];
  facts: FactRecord[];
};

describe("reader-response fixture invariants (ADR-0005)", () => {
  const fixture = load("fixtures/reader-response.json") as {
    as_of: string;
    corpus_version_id: string | null;
    selection_policy: string;
    document: DocBlock;
    siblings: DocBlock[];
  };
  const blocks: DocBlock[] = [fixture.document, ...fixture.siblings];
  const sha256 = (s: string) => "sha256:" + createHash("sha256").update(s, "utf8").digest("hex");

  it("document ids and selected version ids are distinct, never interchangeable", () => {
    const docIds = blocks.map((b) => b.meta.id);
    const verIds = blocks.map((b) => b.document_version_id);
    expect(new Set([...docIds, ...verIds]).size).toBe(docIds.length + verIds.length);
    for (const b of blocks) expect(b.meta.id).not.toBe(b.document_version_id);
  });

  it("every section, span, and fact belongs to its block's selected version", () => {
    for (const b of blocks) {
      for (const s of b.sections ?? []) expect(s.document_version_id).toBe(b.document_version_id);
      for (const r of b.spans) expect(r.span.document_version_id).toBe(b.document_version_id);
      for (const f of b.facts) expect(f.document_version_id).toBe(b.document_version_id);
    }
  });

  it("facts never reference spans absent from their own block", () => {
    for (const b of blocks) {
      const spanIds = new Set(b.spans.map((r) => r.id));
      for (const f of b.facts) expect(spanIds.has(f.fact.source_span_id), f.id).toBe(true);
    }
  });

  it("duplicate_of / restates resolve to fact ids present in the response", () => {
    const factIds = new Set(blocks.flatMap((b) => b.facts.map((f) => f.id)));
    let linkageSeen = 0;
    for (const b of blocks) {
      for (const f of b.facts) {
        if (f.duplicate_of) {
          linkageSeen += 1;
          expect(factIds.has(f.duplicate_of), f.id).toBe(true);
        }
        if (f.restates) {
          linkageSeen += 1;
          expect(factIds.has(f.restates), f.id).toBe(true);
        }
      }
    }
    // The fixture must actually exercise duplicate AND amendment linkage.
    expect(linkageSeen).toBeGreaterThanOrEqual(2);
  });

  it("section offsets are canonical document-global and content is the exact slice length", () => {
    const sections = fixture.document.sections!;
    expect(sections.length).toBeGreaterThan(2);
    for (const s of sections) {
      expect(s.end_char).toBeGreaterThanOrEqual(s.start_char);
      expect(s.content.length).toBe(s.end_char - s.start_char);
    }
    // Non-first sections start where the canonical text has already advanced.
    const ordered = [...sections].sort((a, b) => a.ord - b.ord);
    for (let i = 1; i < ordered.length; i += 1) {
      expect(ordered[i]!.start_char).toBeGreaterThan(0);
      expect(ordered[i]!.start_char).toBeGreaterThanOrEqual(ordered[i - 1]!.end_char);
    }
  });

  it("spans use global offsets: local anchor is start_char - section.start_char and hash-verifies", () => {
    const sections = new Map(fixture.document.sections!.map((s) => [s.id, s]));
    for (const r of fixture.document.spans) {
      const sec = sections.get(r.span.section_id);
      expect(sec, r.id).toBeDefined();
      // Containment in GLOBAL coordinates.
      expect(r.span.start_char).toBeGreaterThanOrEqual(sec!.start_char);
      expect(r.span.end_char).toBeLessThanOrEqual(sec!.end_char);
      // The quoted text re-verifies against the section-content slice.
      const local = sec!.content.slice(
        r.span.start_char - sec!.start_char,
        r.span.end_char - sec!.start_char,
      );
      expect(sha256(local), r.id).toBe(r.span.text_hash);
    }
  });

  it("regression: a non-first-section span's GLOBAL start exceeds its section-content length", () => {
    const sections = new Map(fixture.document.sections!.map((s) => [s.id, s]));
    const witness = fixture.document.spans.find((r) => {
      const sec = sections.get(r.span.section_id)!;
      return sec.ord > 0 && r.span.start_char > sec.content.length;
    });
    // If offsets were section-local this span would be unrepresentable;
    // web's local anchor is start_char - section.start_char (issue #87 B).
    expect(witness).toBeDefined();
  });

  it("cutoff and pin semantics: everything visible at published_at <= as_of; null pin means latest_parsed", () => {
    const asOf = Date.parse(fixture.as_of);
    for (const b of blocks) expect(Date.parse(b.meta.published_at)).toBeLessThanOrEqual(asOf);
    expect(fixture.corpus_version_id).toBeNull();
    expect(fixture.selection_policy).toBe("latest_parsed");
    // Sibling evidence for amendment comparison: same entity throughout.
    for (const b of blocks) expect(b.meta.entity_id).toBe(fixture.document.meta.entity_id);
  });

  it("every fact payload validates against the frozen financial-fact/v1 schema", () => {
    const validate = ajv.getSchema(SCHEMA("financial-fact"))!;
    for (const b of blocks) {
      for (const f of b.facts) {
        expect(validate(f.fact), `${f.id}: ${JSON.stringify(validate.errors)}`).toBe(true);
      }
    }
  });
});

function SCHEMA(name: string): string {
  return `https://contracts.fel.dev/schemas/${name}/v1`;
}
